name: gpodder_api
description: A dart implementation of the gpodder api
version: 0.0.1
author: David Greengas
homepage: https://github.com/harriseldon/gpodder_api

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


